spring:
  application:
    name: msa
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: refresh